### PR TITLE
Added Support for installing without checksums

### PR DESCRIPTION
**Pull request by JohnVictoryz**
Added Support for installing without checksums

### CODE REVIEW

**Review by ilovethensa — CHANGES_REQUESTED** [review]
You should prob make it build first

**Comment by JohnVictoryz** [comment]
> You should prob make it build first

srry :cry:

**Comment by AleksArt000** [comment]
not gonna lie, this does not seem like the most optimal way to do it

**Comment by ilovethensa** [comment]
> not gonna lie, this does not seem like the most optimal way to do it

We can change it later

**Review by AleksArt000 — APPROVED** [review]

**Review by ilovethensa — APPROVED** [review]

**Pull request merged**
